server {
    listen 443 ssl;
    listen [::]:443 ssl; # Écoute aussi en IPv6, très propre pour Inception
    
    server_name lpalabos.42.fr;

    # Configuration SSL (Parfait chez toi !)
    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';

    # 1. AJOUT : Définition de la racine du site (le volume partagé avec WordPress)
    root /var/www/html;
    index index.php index.html index.htm;

    # 2. AJOUT : Gestion des requêtes standards (ex: lpalabos.42.fr/)
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # 3. CORRECTION : Gestion des requêtes PHP
    location ~ \.php$ {
        # On vérifie si le fichier existe via fastcgi directement, ou renvoie 404
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # On passe la requête au conteneur wordpress sur le port 9000
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;

        # Paramètres standards requis pour Debian / Nginx
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}